sudo: required
services:
  - docker

before_install:
  - docker build -t tetrahedral/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tetrahedral/react-test npm test -- --watchAll=false

after_success:
  - docker build -t tetrahedral/multi-client ./client
  - docker build -t tetrahedral/multi-nginx ./nginx
  - docker build -t tetrahedral/multi-server ./server
  - docker build -t tetrahedral/multi-worker ./worker

  # Log in to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push docker images to docker hub
  - docker push tetrahedral/multi-client
  - docker push tetrahedral/multi-nginx
  - docker push tetrahedral/multi-server
  - docker push tetrahedral/multi-worker